name: zapzap
base: core24
adopt-info: zapzap
grade: stable
confinement: strict
summary: WhatsApp desktop client web app
description: |
  ZapZap is a WhatsApp desktop client web app.

apps:
  zapzap:
    command: usr/bin/zapzap
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/x86_64-linux-gnu/libproxy:$SNAP/usr/lib/aarch64-linux-gnu/libproxy:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/usr/local/lib/python3.12/dist-packages:$SNAP/usr/local/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.12/dist-packages:$PYTHONPATH
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - network
      - audio-playback
      - browser-support

parts:
  zapzap:
    plugin: dump
    source: .
    build-packages:
      - python3-build
      - python3-installer
      - python3-venv
    stage-packages:
      - python3
      - python3-pyqt6
      - python3-pyqt6.qtwebengine
    override-build: |
      set -eu
      cd "$CRAFT_PART_SRC"
      . builders/common/common.sh
      craftctl set version="$(project_version)"
      export DESTDIR="$CRAFT_PART_INSTALL"
      export PREFIX=/usr
      prepare_package
