from .appearance_settings_view import AppearanceSettingsView
from .notifications_settings_view import NotificationsSettingsView
from .language_downloads_settings_view import LanguageDownloadSettingsView
from .system_startup_settings_view import SystemStartupSettingsView
from .network_privacy_settings_view import NetworkPrivacySettingsView
from .advanced_customizations_settings_view import AdvancedCustomizationsSettingsView
from .performance_experimental_settings_view import PerformanceExperimentalSettingsView
from .accounts_settings_view import AccountsSettingsView