"""Settings page controllers."""

from .accounts_settings_controller import AccountsSettingsController
from .about_settings_controller import AboutSettingsController
from .appearance_settings_controller import AppearanceSettingsController
from .advanced_customizations_settings_controller import AdvancedCustomizationsSettingsController
from .debugging_settings_controller import DebuggingSettingsController
from .language_downloads_settings_controller import LanguageDownloadsSettingsController
from .network_privacy_settings_controller import NetworkPrivacySettingsController
from .notifications_settings_controller import NotificationsSettingsController
from .performance_experimental_settings_controller import PerformanceExperimentalSettingsController
from .support_settings_controller import SupportSettingsController
from .system_startup_settings_controller import SystemStartupSettingsController
