# Form implementation generated from reading ui file './zapzap/ui/ui_card_user.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CardUser(object):
    def setupUi(self, CardUser):
        CardUser.setObjectName("CardUser")
        CardUser.resize(372, 98)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CardUser)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=CardUser)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QPushButton(parent=self.frame)
        self.icon.setMinimumSize(QtCore.QSize(46, 46))
        self.icon.setMaximumSize(QtCore.QSize(46, 46))
        self.icon.setText("")
        self.icon.setIconSize(QtCore.QSize(46, 46))
        self.icon.setFlat(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.disable = QtWidgets.QPushButton(parent=self.frame)
        self.disable.setStyleSheet("")
        self.disable.setCheckable(True)
        self.disable.setObjectName("disable")
        self.gridLayout.addWidget(self.disable, 1, 1, 1, 1)
        self.silence = QtWidgets.QPushButton(parent=self.frame)
        self.silence.setStyleSheet("")
        self.silence.setCheckable(True)
        self.silence.setObjectName("silence")
        self.gridLayout.addWidget(self.silence, 1, 0, 1, 1)
        self.delete = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete.sizePolicy().hasHeightForWidth())
        self.delete.setSizePolicy(sizePolicy)
        self.delete.setStyleSheet("")
        self.delete.setObjectName("delete")
        self.gridLayout.addWidget(self.delete, 1, 2, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.frame)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(CardUser)
        QtCore.QMetaObject.connectSlotsByName(CardUser)

    def retranslateUi(self, CardUser):
        _translate = QtCore.QCoreApplication.translate
        CardUser.setWindowTitle(_translate("CardUser", "Form"))
        self.icon.setToolTip(_translate("CardUser", "<html><head/><body><p>Clique para gerar novas cores para o ícone</p></body></html>"))
        self.disable.setText(_translate("CardUser", "Desativar"))
        self.silence.setText(_translate("CardUser", "Não pertube"))
        self.delete.setText(_translate("CardUser", "Excluir"))
        self.name.setPlaceholderText(_translate("CardUser", "Enter the user name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CardUser = QtWidgets.QWidget()
    ui = Ui_CardUser()
    ui.setupUi(CardUser)
    CardUser.show()
    sys.exit(app.exec())
