from gettext import gettext as _

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageAbout(object):
    def setupUi(self, PageAbout):
        PageAbout.setObjectName("PageAbout")
        PageAbout.resize(662, 666)
        PageAbout.setWindowTitle("")
        PageAbout.setStyleSheet("QPushButton{\\n}\n"
"QPushButton:pressed{\\n}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PageAbout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(parent=PageAbout)
        self.frame.setMinimumSize(QtCore.QSize(550, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelBuildProvider = QtWidgets.QLabel(parent=self.groupBox)
        self.labelBuildProvider.setObjectName("labelBuildProvider")
        self.gridLayout_2.addWidget(self.labelBuildProvider, 5, 0, 1, 1)
        self.labelBuildCommit = QtWidgets.QLabel(parent=self.groupBox)
        self.labelBuildCommit.setObjectName("labelBuildCommit")
        self.gridLayout_2.addWidget(self.labelBuildCommit, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.icon = QtWidgets.QPushButton(parent=self.groupBox)
        self.icon.setMaximumSize(QtCore.QSize(32, 32))
        self.icon.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.icon.setText("")
        self.icon.setIconSize(QtCore.QSize(32, 32))
        self.icon.setFlat(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout_3.addWidget(self.icon)
        self.name_app = QtWidgets.QLabel(parent=self.groupBox)
        self.name_app.setStyleSheet("font: 12pt bold;")
        self.name_app.setObjectName("name_app")
        self.horizontalLayout_3.addWidget(self.name_app)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.btnLeanMore = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnLeanMore.setObjectName("btnLeanMore")
        self.gridLayout_2.addWidget(self.btnLeanMore, 9, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 7, 0, 1, 1)
        self.labelBuildChannel = QtWidgets.QLabel(parent=self.groupBox)
        self.labelBuildChannel.setObjectName("labelBuildChannel")
        self.gridLayout_2.addWidget(self.labelBuildChannel, 4, 0, 1, 1)
        self.version_app = QtWidgets.QLabel(parent=self.groupBox)
        self.version_app.setObjectName("version_app")
        self.gridLayout_2.addWidget(self.version_app, 2, 0, 1, 1)
        self.btnReportIssue = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnReportIssue.setObjectName("btnReportIssue")
        self.gridLayout_2.addWidget(self.btnReportIssue, 10, 0, 1, 1)
        self.btnDonate = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnDonate.setCheckable(False)
        self.btnDonate.setObjectName("btnDonate")
        self.gridLayout_2.addWidget(self.btnDonate, 8, 0, 1, 1)
        self.qt_version = QtWidgets.QLabel(parent=self.groupBox)
        self.qt_version.setObjectName("qt_version")
        self.gridLayout_2.addWidget(self.qt_version, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 295, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)

        self.retranslateUi(PageAbout)
        QtCore.QMetaObject.connectSlotsByName(PageAbout)

    def retranslateUi(self, PageAbout):
        
        self.label.setText(_("About"))
        self.labelBuildProvider.setText(_("Build Provider: {value}"))
        self.labelBuildCommit.setText(_("Build Commit: {value}"))
        self.name_app.setText(_("name_app"))
        self.btnLeanMore.setText(_("ZapZap official website ->"))
        self.labelBuildChannel.setText(_("Build channel: {value}"))
        self.version_app.setText(_("Version: {id}"))
        self.btnReportIssue.setText(_("Report a problem ->"))
        self.btnDonate.setText(_("Donate to the project ->"))
        self.qt_version.setText(_("Qt: 6.10.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PageAbout = QtWidgets.QWidget()
    ui = Ui_PageAbout()
    ui.setupUi(PageAbout)
    PageAbout.show()
    sys.exit(app.exec())
