from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/ui/ui_shortcuts_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShortcutsDialog(object):
    def setupUi(self, ShortcutsDialog):
        ShortcutsDialog.setObjectName("ShortcutsDialog")
        ShortcutsDialog.resize(798, 575)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShortcutsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=ShortcutsDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(parent=ShortcutsDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_whatsapp = QtWidgets.QTableWidget(parent=self.groupBox)
        self.table_whatsapp.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_whatsapp.setObjectName("table_whatsapp")
        self.table_whatsapp.setColumnCount(0)
        self.table_whatsapp.setRowCount(0)
        self.table_whatsapp.horizontalHeader().setVisible(False)
        self.table_whatsapp.verticalHeader().setVisible(False)
        self.table_whatsapp.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.table_whatsapp)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=ShortcutsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_zapzap = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.table_zapzap.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_zapzap.setObjectName("table_zapzap")
        self.table_zapzap.setColumnCount(0)
        self.table_zapzap.setRowCount(0)
        self.table_zapzap.horizontalHeader().setVisible(False)
        self.table_zapzap.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.table_zapzap)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ShortcutsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ShortcutsDialog)
        self.buttonBox.accepted.connect(ShortcutsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ShortcutsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ShortcutsDialog)

    def retranslateUi(self, ShortcutsDialog):
        
        ShortcutsDialog.setWindowTitle(_("Dialog"))
        self.label.setText(_("Keyboard shortcuts"))
        self.groupBox.setTitle(_("WhatsApp Web"))
        self.groupBox_2.setTitle(_("ZapZap"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShortcutsDialog = QtWidgets.QDialog()
    ui = Ui_ShortcutsDialog()
    ui.setupUi(ShortcutsDialog)
    ShortcutsDialog.show()
    sys.exit(app.exec())
