from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/card_user.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CardUser(object):
    def setupUi(self, CardUser):
        CardUser.setObjectName("CardUser")
        CardUser.resize(320, 77)
        CardUser.setMinimumSize(QtCore.QSize(320, 0))
        CardUser.setWindowTitle("")
        CardUser.setStyleSheet("")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(CardUser)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frameCardUser = QtWidgets.QFrame(parent=CardUser)
        self.frameCardUser.setMinimumSize(QtCore.QSize(320, 0))
        self.frameCardUser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameCardUser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCardUser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCardUser.setObjectName("frameCardUser")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameCardUser)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(parent=self.frameCardUser)
        self.icon.setMinimumSize(QtCore.QSize(46, 46))
        self.icon.setMaximumSize(QtCore.QSize(46, 46))
        self.icon.setText("")
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLineEdit(parent=self.frameCardUser)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelShortcut = QtWidgets.QLabel(parent=self.frameCardUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelShortcut.sizePolicy().hasHeightForWidth())
        self.labelShortcut.setSizePolicy(sizePolicy)
        self.labelShortcut.setObjectName("labelShortcut")
        self.horizontalLayout_2.addWidget(self.labelShortcut)
        self.key = QtWidgets.QLabel(parent=self.frameCardUser)
        self.key.setText("")
        self.key.setObjectName("key")
        self.horizontalLayout_2.addWidget(self.key)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.disableUser = QtWidgets.QCheckBox(parent=self.frameCardUser)
        self.disableUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.disableUser.setText("")
        self.disableUser.setObjectName("disableUser")
        self.gridLayout.addWidget(self.disableUser, 0, 3, 1, 1)
        self.showNotifications = QtWidgets.QCheckBox(parent=self.frameCardUser)
        self.showNotifications.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.showNotifications.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.showNotifications.setText("")
        self.showNotifications.setChecked(True)
        self.showNotifications.setObjectName("showNotifications")
        self.gridLayout.addWidget(self.showNotifications, 0, 2, 1, 1)
        self.deleteUser = QtWidgets.QCheckBox(parent=self.frameCardUser)
        self.deleteUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.deleteUser.setText("")
        self.deleteUser.setObjectName("deleteUser")
        self.gridLayout.addWidget(self.deleteUser, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addWidget(self.frameCardUser)

        self.retranslateUi(CardUser)
        QtCore.QMetaObject.connectSlotsByName(CardUser)

    def retranslateUi(self, CardUser):
        
        self.name.setPlaceholderText(_("Enter the user name"))
        self.labelShortcut.setText(_("Shortcut:"))
        self.disableUser.setToolTip(_("Disable account"))
        self.showNotifications.setToolTip(_("Show notifications"))
        self.deleteUser.setToolTip(_("Delete account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CardUser = QtWidgets.QWidget()
    ui = Ui_CardUser()
    ui.setupUi(CardUser)
    CardUser.show()
    sys.exit(app.exec())
