from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/card_user.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CardUser(object):
    def setupUi(self, CardUser):
        CardUser.setObjectName("CardUser")
        CardUser.resize(620, 104)
        CardUser.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CardUser)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(CardUser)
        self.frame.setMinimumSize(QtCore.QSize(620, 0))
        self.frame.setMaximumSize(QtCore.QSize(620, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btnDisable = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisable.sizePolicy().hasHeightForWidth())
        self.btnDisable.setSizePolicy(sizePolicy)
        self.btnDisable.setMinimumSize(QtCore.QSize(100, 30))
        self.btnDisable.setMaximumSize(QtCore.QSize(100, 30))
        self.btnDisable.setObjectName("btnDisable")
        self.gridLayout.addWidget(self.btnDisable, 0, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setMinimumSize(QtCore.QSize(100, 30))
        self.btnDelete.setMaximumSize(QtCore.QSize(100, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setMinimumSize(QtCore.QSize(64, 64))
        self.icon.setMaximumSize(QtCore.QSize(64, 64))
        self.icon.setText("")
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.gridLayout_3.addWidget(self.icon, 0, 0, 1, 1)
        self.inputGrid = QtWidgets.QGridLayout()
        self.inputGrid.setVerticalSpacing(10)
        self.inputGrid.setObjectName("inputGrid")
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setMinimumSize(QtCore.QSize(0, 30))
        self.name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.inputGrid.addWidget(self.name, 0, 0, 1, 2)
        self.key = QtWidgets.QLineEdit(self.frame)
        self.key.setMinimumSize(QtCore.QSize(70, 30))
        self.key.setMaximumSize(QtCore.QSize(70, 30))
        self.key.setReadOnly(True)
        self.key.setObjectName("key")
        self.inputGrid.addWidget(self.key, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.inputGrid, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(CardUser)
        QtCore.QMetaObject.connectSlotsByName(CardUser)

    def retranslateUi(self, CardUser):
        
        CardUser.setWindowTitle(_("Form"))
        self.btnDisable.setText(_("Disable"))
        self.btnDelete.setText(_("Delete"))
        self.name.setText(_("User 0"))
        self.name.setPlaceholderText(_("Usuário padrão"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CardUser = QtWidgets.QWidget()
    ui = Ui_CardUser()
    ui.setupUi(CardUser)
    CardUser.show()
    sys.exit(app.exec())
