from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/donations_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Donations(object):
    def setupUi(self, Donations):
        Donations.setObjectName("Donations")
        Donations.resize(424, 406)
        Donations.setWindowTitle("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Donations)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Donations)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 424, 406))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_paypal = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_paypal.setText("")
        self.btn_paypal.setObjectName("btn_paypal")
        self.verticalLayout.addWidget(self.btn_paypal)
        self.btn_kofi = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_kofi.setText("")
        self.btn_kofi.setObjectName("btn_kofi")
        self.verticalLayout.addWidget(self.btn_kofi)
        self.btn_pix = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_pix.setText("")
        self.btn_pix.setObjectName("btn_pix")
        self.verticalLayout.addWidget(self.btn_pix)
        self.btn_gitSponor = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_gitSponor.setText("")
        self.btn_gitSponor.setObjectName("btn_gitSponor")
        self.verticalLayout.addWidget(self.btn_gitSponor)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 187, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Donations)
        QtCore.QMetaObject.connectSlotsByName(Donations)

    def retranslateUi(self, Donations):
        
        self.label.setText(_("Donations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Donations = QtWidgets.QWidget()
    ui = Ui_Donations()
    ui.setupUi(Donations)
    Donations.show()
    sys.exit(app.exec())
