from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/downloadPopup.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DownloadPopup(object):
    def setupUi(self, DownloadPopup):
        DownloadPopup.setObjectName("DownloadPopup")
        DownloadPopup.resize(342, 126)
        DownloadPopup.setWindowTitle("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DownloadPopup)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.popupMargins = QtWidgets.QFrame(parent=DownloadPopup)
        self.popupMargins.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.popupMargins.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popupMargins.setObjectName("popupMargins")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.popupMargins)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.popupFrame = QtWidgets.QFrame(parent=self.popupMargins)
        self.popupFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.popupFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popupFrame.setObjectName("popupFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.popupFrame)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.popupFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.popupFrame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.open = QtWidgets.QPushButton(parent=self.frame_3)
        self.open.setObjectName("open")
        self.horizontalLayout_5.addWidget(self.open)
        self.saveAs = QtWidgets.QPushButton(parent=self.frame_3)
        self.saveAs.setObjectName("saveAs")
        self.horizontalLayout_5.addWidget(self.saveAs)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.popupFrame)
        self.verticalLayout_3.addWidget(self.popupMargins)

        self.retranslateUi(DownloadPopup)
        QtCore.QMetaObject.connectSlotsByName(DownloadPopup)

    def retranslateUi(self, DownloadPopup):
        
        self.label_2.setText(_("What do you want to do with the file?"))
        self.open.setText(_("Open"))
        self.saveAs.setText(_("Save as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DownloadPopup = QtWidgets.QWidget()
    ui = Ui_DownloadPopup()
    ui.setupUi(DownloadPopup)
    DownloadPopup.show()
    sys.exit(app.exec())
