from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/templates/drawer.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_drawer(object):
    def setupUi(self, drawer):
        drawer.setObjectName("drawer")
        drawer.setEnabled(True)
        drawer.resize(828, 509)
        drawer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        drawer.setMouseTracking(False)
        drawer.setAutoFillBackground(True)
        drawer.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(drawer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.blur = QtWidgets.QWidget(drawer)
        self.blur.setAutoFillBackground(False)
        self.blur.setObjectName("blur")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blur)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(520, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_drawer = QtWidgets.QFrame(self.blur)
        self.frame_drawer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_drawer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_drawer.setObjectName("frame_drawer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_drawer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutSettings = QtWidgets.QVBoxLayout()
        self.layoutSettings.setObjectName("layoutSettings")
        self.verticalLayout_2.addLayout(self.layoutSettings)
        self.verticalLayout.addWidget(self.frame_drawer)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(519, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.blur)
        self.openDrawerButton = QtWidgets.QPushButton(drawer)
        self.openDrawerButton.setMinimumSize(QtCore.QSize(7, 150))
        self.openDrawerButton.setMaximumSize(QtCore.QSize(7, 150))
        self.openDrawerButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.openDrawerButton.setText("")
        self.openDrawerButton.setObjectName("openDrawerButton")
        self.horizontalLayout_2.addWidget(self.openDrawerButton)

        self.retranslateUi(drawer)
        QtCore.QMetaObject.connectSlotsByName(drawer)

    def retranslateUi(self, drawer):
        
        drawer.setWindowTitle(_("Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    drawer = QtWidgets.QWidget()
    ui = Ui_drawer()
    ui.setupUi(drawer)
    drawer.show()
    sys.exit(app.exec())
