# Form implementation generated from reading ui file '/home/tosta/Documentos/GitHub/zapzap/zapzap/view/drawer.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_drawer(object):
    def setupUi(self, drawer):
        drawer.setObjectName("drawer")
        drawer.setEnabled(True)
        drawer.resize(828, 509)
        drawer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        drawer.setMouseTracking(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(drawer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.blur = QtWidgets.QWidget(drawer)
        self.blur.setObjectName("blur")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blur)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(520, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(self.blur)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.horizontalLayout.addWidget(self.stackedWidget)
        spacerItem1 = QtWidgets.QSpacerItem(519, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.blur)
        self.openDrawerButton = QtWidgets.QPushButton(drawer)
        self.openDrawerButton.setMinimumSize(QtCore.QSize(5, 150))
        self.openDrawerButton.setMaximumSize(QtCore.QSize(5, 150))
        self.openDrawerButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.openDrawerButton.setText("")
        self.openDrawerButton.setObjectName("openDrawerButton")
        self.horizontalLayout_2.addWidget(self.openDrawerButton)

        self.retranslateUi(drawer)
        QtCore.QMetaObject.connectSlotsByName(drawer)

    def retranslateUi(self, drawer):
        _translate = QtCore.QCoreApplication.translate
        drawer.setWindowTitle(_translate("drawer", "Form"))
