from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menubar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuChat = QtWidgets.QMenu(parent=self.menubar)
        self.menuChat.setObjectName("menuChat")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setShortcut("Ctrl+P")
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionQuit.setObjectName("actionQuit")
        self.actionReload_Service = QtGui.QAction(parent=MainWindow)
        self.actionReload_Service.setShortcut("F5")
        self.actionReload_Service.setObjectName("actionReload_Service")
        self.actionDefault_size_page = QtGui.QAction(parent=MainWindow)
        self.actionDefault_size_page.setShortcut("Ctrl+0")
        self.actionDefault_size_page.setObjectName("actionDefault_size_page")
        self.actionToggle_Full_Screen = QtGui.QAction(parent=MainWindow)
        self.actionToggle_Full_Screen.setShortcut("F11")
        self.actionToggle_Full_Screen.setObjectName("actionToggle_Full_Screen")
        self.actionZoomIn = QtGui.QAction(parent=MainWindow)
        self.actionZoomIn.setShortcut("Ctrl++")
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtGui.QAction(parent=MainWindow)
        self.actionZoomOut.setShortcut("Ctrl+-")
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionOpen_new_chat = QtGui.QAction(parent=MainWindow)
        self.actionOpen_new_chat.setShortcut("Ctrl+N")
        self.actionOpen_new_chat.setObjectName("actionOpen_new_chat")
        self.actionHide = QtGui.QAction(parent=MainWindow)
        self.actionHide.setObjectName("actionHide")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionHide)
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionReload_Service)
        self.menuView.addAction(self.actionDefault_size_page)
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionToggle_Full_Screen)
        self.menuChat.addAction(self.actionOpen_new_chat)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuChat.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        
        MainWindow.setWindowTitle(_("ZapZap"))
        self.menuFile.setTitle(_("File"))
        self.menuView.setTitle(_("View"))
        self.menuChat.setTitle(_("Chat"))
        self.actionSettings.setText(_("Settings"))
        self.actionQuit.setText(_("Quit"))
        self.actionReload_Service.setText(_("Reload"))
        self.actionDefault_size_page.setText(_("Default size page"))
        self.actionToggle_Full_Screen.setText(_("Full Screen"))
        self.actionZoomIn.setText(_("Zoom in"))
        self.actionZoomOut.setText(_("Zoom out"))
        self.actionOpen_new_chat.setText(_("Open new chat"))
        self.actionHide.setText(_("Hide"))
        self.actionHide.setShortcut(_("Ctrl+W"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
