from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/templates/settings_system.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 363)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_system = QtWidgets.QCheckBox(self.groupBox)
        self.start_system.setObjectName("start_system")
        self.verticalLayout.addWidget(self.start_system)
        self.start_hide = QtWidgets.QCheckBox(self.groupBox)
        self.start_hide.setEnabled(False)
        self.start_hide.setObjectName("start_hide")
        self.verticalLayout.addWidget(self.start_hide)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.keepBackground = QtWidgets.QCheckBox(self.groupBox)
        self.keepBackground.setChecked(True)
        self.keepBackground.setObjectName("keepBackground")
        self.verticalLayout_3.addWidget(self.keepBackground)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.night_mode = QtWidgets.QCheckBox(self.groupBox)
        self.night_mode.setObjectName("night_mode")
        self.verticalLayout_4.addWidget(self.night_mode)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        
        Form.setWindowTitle(_("Form"))
        self.groupBox.setTitle(_("System integration"))
        self.start_system.setText(_("Start ZapZap with the system"))
        self.start_hide.setText(_("Start minimized"))
        self.keepBackground.setText(_("Keep in background when closing window"))
        self.night_mode.setText(_("Night mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
