from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/templates/settings_notify.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(749, 482)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notify_desktop = QtWidgets.QCheckBox(self.groupBox_2)
        self.notify_desktop.setChecked(True)
        self.notify_desktop.setObjectName("notify_desktop")
        self.verticalLayout.addWidget(self.notify_desktop)
        self.show_photo = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_photo.setEnabled(True)
        self.show_photo.setChecked(True)
        self.show_photo.setObjectName("show_photo")
        self.verticalLayout.addWidget(self.show_photo)
        self.show_name = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_name.setEnabled(True)
        self.show_name.setChecked(True)
        self.show_name.setObjectName("show_name")
        self.verticalLayout.addWidget(self.show_name)
        self.show_msg = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_msg.setEnabled(True)
        self.show_msg.setChecked(True)
        self.show_msg.setObjectName("show_msg")
        self.verticalLayout.addWidget(self.show_msg)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.symbolic_icon = QtWidgets.QCheckBox(self.groupBox)
        self.symbolic_icon.setObjectName("symbolic_icon")
        self.verticalLayout_2.addWidget(self.symbolic_icon)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 218, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        
        Form.setWindowTitle(_("Form"))
        self.groupBox_2.setTitle(_("Chat notifications"))
        self.notify_desktop.setText(_("Notifications on the desktop"))
        self.show_photo.setText(_("Show the photo of the sender"))
        self.show_name.setText(_("Show the sender\'s name"))
        self.show_msg.setText(_("Show message preview"))
        self.groupBox.setTitle(_("TrayIcon"))
        self.symbolic_icon.setText(_("Symbolic icon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
