from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/templates/settings_about.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 375)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.icon = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMinimumSize(QtCore.QSize(200, 200))
        self.icon.setMaximumSize(QtCore.QSize(200, 200))
        self.icon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.icon.setScaledContents(False)
        self.icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.version = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.version.setObjectName("version")
        self.verticalLayout.addWidget(self.version)
        self.description_app = QtWidgets.QLabel(self.groupBox)
        self.description_app.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.description_app.setObjectName("description_app")
        self.verticalLayout.addWidget(self.description_app)
        self.webpage = QtWidgets.QLabel(self.groupBox)
        self.webpage.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.webpage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.webpage.setOpenExternalLinks(True)
        self.webpage.setObjectName("webpage")
        self.verticalLayout.addWidget(self.webpage)
        self.developer = QtWidgets.QLabel(self.groupBox)
        self.developer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.developer.setObjectName("developer")
        self.verticalLayout.addWidget(self.developer)
        self.license = QtWidgets.QLabel(self.groupBox)
        self.license.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.license.setObjectName("license")
        self.verticalLayout.addWidget(self.license)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        
        Form.setWindowTitle(_("Form"))
        self.groupBox.setTitle(_("GroupBox"))
        self.icon.setText(_("icone do app"))
        self.version.setText(_("versão"))
        self.description_app.setText(_("descrição"))
        self.webpage.setText(_("pagina na web"))
        self.developer.setText(_("Desenvolvedor"))
        self.license.setText(_("GNU General Public License v3.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
