from gettext import gettext as _


class SpellCheckLanguages():
    languages = {
        "af_NA": _("Afrikaans - Namibia"),
        "af_ZA": _("Afrikaans - South Africa"),
        "an": _("Aragonese"),
        "an_ES": _("Aragonese - Spain"),
        "ar_AE": _("Arabic - United Arab Emirates"),
        "ar_BH": _("Arabic - Bahrain"),
        "ar_DZ": _("Arabic - Algeria"),
        "ar_EG": _("Arabic - Egypt"),
        "ar_IQ": _("Arabic - Iraq"),
        "ar_JO": _("Arabic - Jordan"),
        "ar_KW": _("Arabic - Kuwait"),
        "ar_LB": _("Arabic - Lebanon"),
        "ar_LY": _("Arabic - Libya"),
        "ar_MA": _("Arabic - Morocco"),
        "ar_OM": _("Arabic - Oman"),
        "ar_QA": _("Arabic - Qatar"),
        "ar_SA": _("Arabic - Saudi Arabia"),
        "ar_SD": _("Arabic - Sudan"),
        "ar_SY": _("Arabic - Syria"),
        "ar_TN": _("Arabic - Tunisia"),
        "ar_YE": _("Arabic - Yemen"),
        "be_BY": _("Belarusian - Belarus"),
        "bg_BG": _("Bulgarian - Bulgaria"),
        "bn_BD": _("Bengali - Bangladesh"),
        "bn_IN": _("Bengali - India"),
        "bo": _("Tibetan"),
        "bo_CN": _("Tibetan - China"),
        "bo_IN": _("Tibetan - India"),
        "br_FR": _("Breton - France"),
        "bs": _("Bosnian"),
        "bs_BA": _("Bosnian - Bosnia and Herzegovina"),
        "ca_AD": _("Catalan - Andorra"),
        "ca_ES": _("Catalan - Spain"),
        "ca_ES-valencia": _("Catalan - Valencia"),
        "ca_FR": _("Catalan - France"),
        "ca_IT": _("Catalan - Italy"),
        "cs_CZ": _("Czech - Czechia"),
        "da_DK": _("Danish - Denmark"),
        "de_AT": _("German - Austria"),
        "de_CH": _("German - Switzerland"),
        "de_DE": _("German - Germany"),
        "el_GR": _("Greek - Grece"),
        "en_AU": _("English - Australia"),
        "en_BS": _("English - Bahamas"),
        "en_BZ": _("English - Belize"),
        "en_CA": _("English - Canada"),
        "en_GB": _("English - United Kingdom"),
        "en_GH": _("English - Ghana"),
        "en_IE": _("English - Ireland"),
        "en_IN": _("English - India"),
        "en_JM": _("English - Jamaica"),
        "en_MW": _("English - Malawi"),
        "en_NA": _("English - Namibia"),
        "en_NZ": _("English - New Zealand"),
        "en_PH": _("English - Philippines"),
        "en_TT": _("English - Trinidad and Tobago"),
        "en_US": _("English - United States of America"),
        "en_ZA": _("English - South Africa"),
        "en_ZW": _("English - Zimbabwe"),
        "es_AR": _("Spanish - Argentina"),
        "es_BO": _("Spanish - Bolivia"),
        "es_CL": _("Spanish - Chile"),
        "es_CO": _("Spanish - Colombia"),
        "es_CR": _("Spanish - Costa Rica"),
        "es_CU": _("Spanish - Cuba"),
        "es_DO": _("Spanish - Dominican Republic"),
        "es_EC": _("Spanish - Ecuador"),
        "es_ES": _("Spanish - Spain"),
        "es_GT": _("Spanish - Guatemala"),
        "es_HN": _("Spanish - Honduras"),
        "es_MX": _("Spanish - Mexico"),
        "es_NI": _("Spanish - Nicaragua"),
        "es_PA": _("Spanish - Panama"),
        "es_PE": _("Spanish - Peru"),
        "es_PR": _("Spanish - Puerto Rico"),
        "es_PY": _("Spanish - Paraguay"),
        "es_SV": _("Spanish - El Salvador"),
        "es_UY": _("Spanish - Uruguay"),
        "es_VE": _("Spanish - Venezuela"),
        "et_EE": _("Estonian - Estonia"),
        "fr_BE": _("French - Belgium"),
        "fr_CA": _("French - Canada"),
        "fr_CH": _("French - Switzerland"),
        "fr_FR": _("French - France"),
        "fr_LU": _("French - Luxembourg"),
        "fr_MC": _("French - Monaco"),
        "gd_GB": _("Scottish Gaelic - United Kingdom"),
        "gug_PY": _("Guarani - Paraguay"),
        "he_IL": _("Hebrew - Israel"),
        "hi_IN": _("Hindi - India"),
        "hr_HR": _("Croatian - Croatia"),
        "hu_HU": _("Hungary - Hungarian"),
        "id_ID": _("Indonesian - Indonesia"),
        "is": _("Icelandic"),
        "is_IS": _("Icelandic - Iceland"),
        "it_IT": _("Italian - Italy"),
        "kmr-Latn_SY": _("Kurdish Latin - Syria"),
        "kmr-Latn_TR": _("Kurdish Latin - Turkey"),
        "lo_LA": _("Lao - Laos"),
        "lt_LT": _("Lithuanian - Lithuania"),
        "lv_LV": _("Latvian - Latvia"),
        "nb_NO": _("Norwegian - Bokmål"),
        "ne_NP": _("Nepali - Nepal"),
        "nl_BE": _("Dutch - Belgium"),
        "nl_NL": _("Dutch - Netherlands"),
        "nn_NO": _("Norwegian - Nynorsk"),
        "oc_FR": _("Occitan - France"),
        "pl_PL": _("Polish - Poland"),
        "pt_AO": _("Portuguese - Angola"),
        "pt_BR": _("Portuguese - Brazil"),
        "pt_PT": _("Portuguese - Portugal"),
        "ro_RO": _("Romanian - Romania"),
        "ru_RU": _("Russian - Russia"),
        "si_LK": _("Sinhala - Sri Lanka"),
        "sk_SK": _("Slovak - Slovakia"),
        "sl_SI": _("Slovenian - Slovenia"),
        "sq_AL": _("Albanian - Albania"),
        "sr_CS": _("Serbian - Czechia"),
        "sr-Latn_CS": _("Serbian Latin - Czechia"),
        "sr-Latn_RS": _("Serbian Latin - Serbia"),
        "sr_RS": _("Serbian - Serbia"),
        "sv_FI": _("Swedish - Finland"),
        "sv_SE": _("Swedish - Sweden"),
        "sw_TZ": _("Swahili - Tanzania"),
        "te": _("Telugu"),
        "te_IN": _("Telugu - India"),
        "tr": _("Turkish"),
        "tr_TR": _("Turkish - Turkey"),
        "uk_UA": _("Ukrainian - Ukraine"),
        "vi_VN": _("Vietnamese - Vietnam")
    }
