name: Build RPM

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_upload:
        required: false
        type: boolean
        default: false
      release_tag:
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  build-rpm:
    name: Build RPM (${{ matrix.rpm_arch }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            rpm_arch: x86_64

          - runner: ubuntu-24.04-arm
            rpm_arch: aarch64

    container:
      image: fedora:44

    steps:
      - name: Install build tools
        run: |
          dnf -y update
          dnf -y install \
            git \
            rpm-build \
            rpmdevtools \
            python3-devel \
            pyproject-rpm-macros \
            desktop-file-utils \
            libappstream-glib \
            python3-pyqt6 \
            python3-pyqt6-webengine \
            python3-dbus

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set packaging scripts executable
        run: |
          chmod +x .github/packaging/common/version.sh  
          chmod +x .github/packaging/rpm/build.sh
          chmod +x .github/packaging/rpm/normalize.sh
          chmod +x .github/packaging/common/build-info.sh

      - name: Create BuildInfo.py
        run: .github/packaging/common/build-info.sh "RPM"

      - name: Build RPM
        run: .github/packaging/rpm/build.sh

      - name: Normalize RPM names
        run: .github/packaging/rpm/normalize.sh "${{ matrix.rpm_arch }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zapzap-rpm-${{ matrix.rpm_arch }}
          path: dist-rpm/*.rpm

      - name: Upload RPMs to release
        if: ${{ inputs.release_upload == true || github.event.inputs.release_upload == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag || github.event.inputs.release_tag || github.ref_name }}
          files: dist-rpm/*.rpm
