name: Build and Release Zapzap

on:
  workflow_dispatch:
     inputs:
      publish:
        description: "Criar release?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

  release:
    types: [created]

  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.14"

jobs:
# ==========================================================
# PYTHON PACKAGE
# ==========================================================

  build-python:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create BuildInfo.py
        shell: bash
        run: |
          cat > zapzap/BuildInfo.py << EOF
          BUILD_CHANNEL = "Official"
          BUILD_PROVIDER = "GitHub Actions"
          BUILD_REPOSITORY = "${{ github.repository }}"
          EOF

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist

      - name: List generated files
        run: |
          ls -lah dist/

      # ======================================================
      # Manual execution -> upload artifact only
      # ======================================================

      - name: Upload Python artifact
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ZapZap-Python
          path: dist/*.whl

      # ======================================================
      # Release/tag -> publish release
      # ======================================================

      - name: Release Python artifacts
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.publish == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ==========================================================
# WINDOWS
# ==========================================================

  build-windows:
    runs-on: windows-latest

    env:
      PYTHONUTF8: 1

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create BuildInfo.py
        shell: bash
        run: |
          cat > zapzap/BuildInfo.py << EOF
          BUILD_CHANNEL = "Official"
          BUILD_PROVIDER = "GitHub Actions"
          BUILD_REPOSITORY = "${{ github.repository }}"
          EOF

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows executable
        run: |
          python -m builders.windows_builder

      - name: List generated files
        run: |
          dir dist

      # ======================================================
      # Manual execution -> upload artifact only
      # ======================================================

      - name: Upload Windows artifact
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ZapZap-Windows
          path: dist/ZapZap-Windows.zip

      # ======================================================
      # Release/tag -> publish release
      # ======================================================

      - name: Release Windows artifacts
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.publish == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/ZapZap-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ==========================================================
# APPIMAGE
# ==========================================================

  build-appimage:
    runs-on: ubuntu-24.04

    env:
      PYTHONUTF8: 1

    steps: 

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create BuildInfo.py
        shell: bash
        run: |
          cat > zapzap/BuildInfo.py << EOF
          BUILD_CHANNEL = "Official"
          BUILD_PROVIDER = "GitHub Actions"
          BUILD_REPOSITORY = "${{ github.repository }}"
          EOF

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            build-essential \
            python3-dev \
            pkg-config \
            patchelf \
            desktop-file-utils \
            fuse \
            wget \
            unzip \
            curl \
            libdbus-1-dev \
            libdbus-glib-1-dev \
            libglib2.0-dev \
            libegl1 \
            libopengl0 \
            libxkbcommon-x11-0 \
            libnss3 \
            libxss1 \
            libasound2t64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Show versions
        run: |
          python --version
          pip show PyQt6
          pip show PyQt6-WebEngine
          pip show PyInstaller

      - name: Define version
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "VERSION=dev" >> $GITHUB_ENV
          fi

      - name: Build AppImage
        run: |
          python -m builders.appimage_builder ${{ env.VERSION }}

      - name: List generated files
        run: |
          ls -lah dist/

      # ======================================================
      # Manual execution -> upload artifact only
      # ======================================================

      - name: Upload AppImage artifact
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ZapZap-AppImage
          path: dist/*.AppImage

      # ======================================================
      # Release/tag -> publish release
      # ======================================================

      - name: Release AppImage artifacts
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.publish == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# ==========================================================
# APPIMAGE (sharun + uruntime)
# ==========================================================
  build-anylinux-appimage:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          # comment out these 3 lines if aarch64 is not wanted
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2
      - name: Install Dependencies
        run: /bin/sh ./builders/anylinux-appImage/get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./builders/anylinux-appImage/make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

    release:
      if: ${{ github.ref_name == 'main' }}
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
          with:
            pattern: AppImage-*
            merge-multiple: true
        - name: Release AppImage
          uses: pkgforge-dev/make-stable-appimage-release@4ed3d48ccb065352b6e6c0db6d39885b201c54a0 #v1.1